FROM python:3.11-slim

EXPOSE 8000

WORKDIR /opt/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV POETRY_VIRTUALENVS_CREATE 0
ENV POETRY_NO_INTERACTION 1


COPY poetry.lock pyproject.toml /opt/app/

RUN apt update
RUN pip install poetry
RUN poetry config virtualenvs.create false && poetry install

COPY . .

ENTRYPOINT python -m main